import type { Metadata } from 'next'
import Footer from '../Footer'
import Card from '../Card'
import { ArrowIcon } from '../icons'
import { PROJECTS } from '@/lib/projects'

const DESCRIPTION =
  'Engineering and research write-ups — including a full case study on building this portfolio tracker with Next.js, Supabase, and Vercel.'

export const metadata: Metadata = {
  title: 'Projects',
  description: DESCRIPTION,
  alternates: { canonical: '/projects' },
  // `images` repeated deliberately -- see the note in app/experience/page.tsx.
  openGraph: {
    title: 'Projects | Aiden Loc',
    description: DESCRIPTION,
    url: '/projects',
    images: ['/opengraph-image'],
  },
}

function Tag({ children }: { children: React.ReactNode }) {
  return (
    <span className="text-xs uppercase tracking-widest text-gray-500 border border-[var(--color-text)]/15 rounded-[var(--border-radius)] px-2.5 py-1">
      {children}
    </span>
  )
}

export default function ProjectsPage() {
  return (
    <>
      <div className="max-w-2xl">
        <p className="text-xs uppercase tracking-wide text-gray-500 mb-2">Projects</p>
        <h1 className="text-4xl font-bold mb-8">Research &amp; Modeling</h1>

        <Card>
          {/* Title/tags come from lib/projects so the home page's preview card
              can reference this project without restating it. */}
          <p className="text-xs text-gray-600 mb-2">{PROJECTS[0].number}</p>
          <h2 className="text-2xl font-bold mb-3">{PROJECTS[0].title}</h2>
          <div className="flex flex-wrap gap-2 mb-6">
            {PROJECTS[0].tags.map((tag) => (
              <Tag key={tag}>{tag}</Tag>
            ))}
          </div>

          <div className="space-y-6 text-sm text-gray-400 leading-relaxed">
            <div>
              <h3 className="text-[var(--color-text)] font-semibold mb-2">Why I built this</h3>
              <p>
                I wanted a way to practice equity research and portfolio management the way a real analyst
                would — sizing positions, tracking a thesis against a benchmark, and revisiting calls as new
                information comes in — without needing real capital on the line. Building the tracker myself,
                rather than using an existing brokerage's paper-trading tool, meant I could also treat it as a
                second project: a hands-on way to learn full-stack engineering, from database design through
                to shipping and operating a live product.
              </p>
            </div>

            <div>
              <h3 className="text-[var(--color-text)] font-semibold mb-2">Architecture</h3>
              <p className="mb-3">
                The site is a Next.js (App Router) application written in TypeScript and deployed on Vercel.
                Data lives in Supabase (Postgres), accessed two different ways depending on who's asking:
                public pages read through an anon key restricted by row-level security to SELECT-only access,
                while writes (adding a position, editing the theme) go through a service-role client that's
                only reachable from server-side API routes gated behind a signed session cookie. That split
                means the public site can never write to the database, regardless of what a visitor's browser
                sends.
              </p>
              <p>
                A small theme system sits on top of this: colors, spacing, font, and border radius are stored
                as a single settings row and rendered as CSS custom properties on every page load, so the
                entire site's look can be adjusted from the admin panel without a code change or redeploy.
              </p>
            </div>

            <div>
              <h3 className="text-[var(--color-text)] font-semibold mb-2">Where the data comes from</h3>
              <p className="mb-3">
                Historical price series (the performance chart, individual ticker charts) come from Yahoo
                Finance's public chart endpoint — the only source I found with free historical data at this
                granularity. Live quotes, sector classification, company news, and the earnings calendar come
                from Finnhub's free tier. The performance chart itself indexes the portfolio and the S&amp;P
                500 to 0% at the start of whichever window is selected (1D through 1Y), rather than showing a
                raw since-inception curve zoomed in — the same convention fund fact sheets use, so the chart
                actually answers "how did this period go" instead of just "what's the number today."
              </p>
              <p>
                Sector data is fetched once per holding and cached in the database rather than looked up on
                every page load, and the daily briefing is generated by a single Vercel Cron job once a day
                rather than on every visit — both deliberate choices to stay well inside a free API tier's
                rate limits as the number of visitors and holdings grows.
              </p>
            </div>

            <div>
              <h3 className="text-[var(--color-text)] font-semibold mb-2">What this taught me</h3>
              <p>
                Most of the real engineering here wasn't the charting or the styling — it was the boring
                parts that matter in production: making sure admin edits actually invalidate the right cached
                data, checking that a database write actually succeeded instead of assuming it did, and
                thinking about what a public, unauthenticated visitor's browser is and isn't allowed to do to
                the database. Those are the same habits — verify the data, don't trust a green checkmark, know
                exactly who can touch what — that show up in equity research too.
              </p>
            </div>
          </div>

          <a
            href="https://github.com/aidenloc/stock-portfolio-site"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-xs uppercase tracking-wide text-gray-400 hover:text-[var(--color-text)] transition-colors mt-6"
          >
            View Source on GitHub <ArrowIcon />
          </a>
        </Card>
      </div>

      <Footer />
    </>
  )
}
